host: http://localhost:8080
environment: development

database:
  host: localhost
  port: 3307
  user: root
  password: password
  name: oidc

portal:
  database:
    host: localhost
    port: 3306
    user: root
    password: password
    name: portal

oauth:
  test_user_id: testuser
